### ISSUE TITLE
Make the images translatable

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/smoothielanding#36]
### What

```[tasklist]
### Tasks
- [ ] https://github.com/openfoodfacts/smoothielanding/issues/39
- [ ] https://github.com/openfoodfacts/smoothielanding/issues/38
- [ ] https://github.com/openfoodfacts/smoothielanding/issues/37
- [ ] https://github.com/openfoodfacts/smoothielanding/issues/40
```
